cmake_minimum_required(VERSION 3.27)
set(PluginName PluginAmdQuote)
project(${PluginName})

include(../template.cmake)
CreatePlugin(${PluginName})

set(CMAKE_SKIP_RPATH TRUE)
set(PLUGIN_LINK_OPTIONS "-Wl,-rpath,$ORIGIN,-disable-new-dtags")
if(NOT DEFINED AMD_SDK_DIR)
    set(AMD_SDK_DIR ${CMAKE_SOURCE_DIR})
endif()
message(STATUS "AMD_SDK_DIR: ${AMD_SDK_DIR}")
message(STATUS "AMD_VERSION: ${AMD_VERSION}")

target_compile_definitions(${PluginName} PRIVATE "-DAMD_${AMD_VERSION}")
set(PluginConfig ${CMAKE_CURRENT_BINARY_DIR}/${PluginName}.txt)
if(${AMD_VERSION} LESS 398)
    add_custom_command(TARGET ${PluginName} POST_BUILD COMMAND sed -i "9,10d" ${PluginConfig})
elseif(${AMD_VERSION} GREATER 398)
    target_compile_definitions(${PluginName} PRIVATE -DAMD_TRADE_ORDER_VOLUME)
endif()
target_compile_options(${PluginName} PRIVATE -rdynamic)
target_include_directories(${PluginName} PRIVATE ${AMD_SDK_DIR}/include src)
target_link_directories(${PluginName} PRIVATE ${AMD_SDK_DIR}/lib)
target_link_libraries(${PluginName} ${PLUGIN_LINK_OPTIONS} ama)

if (${CMAKE_BUILD_TYPE} MATCHES ASAN)
    add_definitions(-DAMD_USE_ASAN)
endif ()

cmake_path(GET CMAKE_CURRENT_SOURCE_DIR FILENAME INSTALL_DIR)
install(DIRECTORY ${AMD_SDK_DIR}/lib/ DESTINATION ${INSTALL_DIR})
install(FILES ${PluginConfig} DESTINATION ${INSTALL_DIR} RENAME ${PluginName}${AMD_VERSION}.txt)
