cmake_minimum_required(VERSION 3.13)
project(DDBPlugins)

add_subdirectory(AMDHistory)
# add_subdirectory(amdQuote)
add_subdirectory(ami)
add_subdirectory(arrow)
add_subdirectory(ASTTrader)
add_subdirectory(aws)
# add_subdirectory(Backtest)
add_subdirectory(barraopt)
add_subdirectory(ctp)
add_subdirectory(DataFeed)
add_subdirectory(EFH)
add_subdirectory(EncoderDecoder)
add_subdirectory(feather)
add_subdirectory(gp)
add_subdirectory(gurobi)
add_subdirectory(hbase)
add_subdirectory(hdf5)
# add_subdirectory(hdfs)
add_subdirectory(httpClient)
add_subdirectory(insight)
add_subdirectory(kafka)
add_subdirectory(kdb)
add_subdirectory(LDAP)
add_subdirectory(lgbm)
# add_subdirectory(LibTorch)
add_subdirectory(mat)
add_subdirectory(MatchingEngine)
add_subdirectory(MatchingEngineSimulator)
add_subdirectory(MDL)
add_subdirectory(mongodb)
# add_subdirectory(mqtt)
add_subdirectory(mseed)
add_subdirectory(mysql)
add_subdirectory(nsq)
add_subdirectory(odbc)
add_subdirectory(opcua)
add_subdirectory(orc)
# add_subdirectory(OrderManagementEngine)
add_subdirectory(parquet)
add_subdirectory(pulsar)
add_subdirectory(python)
add_subdirectory(QuantLib)
add_subdirectory(rabbitmq)
add_subdirectory(redis)
add_subdirectory(RocketMQ)
add_subdirectory(SchemalessWriter)
add_subdirectory(SevenZip)
add_subdirectory(signal)
add_subdirectory(SimulatedExchangeEngine)
add_subdirectory(SipUI2)
add_subdirectory(SSEQuotationFile)
add_subdirectory(svm)
add_subdirectory(TCPSocket)
add_subdirectory(udpserver)
add_subdirectory(UniqueID)
add_subdirectory(WebSocket)
add_subdirectory(WindTDF)
add_subdirectory(xgboost)
add_subdirectory(XTP)
add_subdirectory(zip)
add_subdirectory(zlib)
add_subdirectory(zmq)
