#ifndef INCLUDE_URLENCODE_VERSION_H_
#define INCLUDE_URLENCODE_VERSION_H_

#define URLENCODE_VERSION_MAJOR 1
#define URLENCODE_VERSION_MINOR 1
#define URLENCODE_VERSION_PATCH 0

#endif  // INCLUDE_URLENCODE_VERSION_H_
