# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data/test_repeat_1_no_string.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"data/test_repeat_1_no_string.proto\"=\n\rtest_repeat_1\x12\x0e\n\x06\x64ouble\x18\x01 \x01(\x01\x12\r\n\x05\x66loat\x18\x02 \x01(\x02\x12\r\n\x05int32\x18\x03 \x03(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data.test_repeat_1_no_string_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEST_REPEAT_1._serialized_start=38
  _TEST_REPEAT_1._serialized_end=99
# @@protoc_insertion_point(module_scope)
